[build-system]
requires = ["maturin>=1.8,<2"]
build-backend = "maturin"

[project]
name = "a2ltool"
requires-python = ">=3.9"
dynamic = [
    "version",
    "description",
    "readme",
    "authors",
    "license",
    "keywords",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Manufacturing",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://github.com/DanielT/a2ltool"
Repository = "https://github.com/DanielT/a2ltool"
Issues = "https://github.com/DanielT/a2ltool/issues"

[tool.maturin]
bindings = "bin"
strip = true

[tool.cibuildwheel]
test-command = "a2ltool --version"
build-frontend = "uv"
