name: Build User Manual

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build User Manual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache Rust artifacts
        # cache all dependencies to speed up the workflow
        uses: Swatinem/rust-cache@v2

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install mdbook and plugins
        run: |
          cargo install mdbook
          cargo install mdbook-pandoc

      - name: Install Pandoc & LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc \
            texlive-latex-base texlive-latex-extra \
            texlive-fonts-recommended lmodern

      - name: Build HTML docs
        run: cd manual && mdbook build

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: manual/book/html

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf-docs
          path: manual/book/pandoc/pdf/a2ltool_manual.pdf
      
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4