name: Rust build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Git LFS
      run: git lfs install --system --skip-repo

    - name: Checkout LFS objects
      run: git lfs pull

    - name: Build
      run: cargo build --release

    - name: Run tests
      env:
        RUST_BACKTRACE: 1
      run: cargo test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        #run: cargo clippy --all-targets --all-features -- -D warnings
        run: cargo clippy --all-features -- -D warnings


